when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.12-jdk17-alpine@sha256:f7fed35a73547d9b76d84efd68618b85c9c0ae6deefbcc6a9a4a2f1d916211a8
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
